Adds /bigobj flag to MSVC
This was removed from blt after release 0.7.1 but is necessary for Axom.
Without this, I was getting `error C1128: number of sections exceeded object file format limit'.