Use standard c_loc instead of shroud_c_loc
shroud_c_loc was added to work around a compiler problem with gfortran
4.7.1.  Using an assumed shape array with c_loc produced a compile
error.  gfortran also seems to have a problem using a NULL pointer
returned from shroud_c_loc with c_associated.  But only with optimized
code.

Instead of kludging another work around for gfortran 4.7.1, I added
ENABLE_FORTRAN=OFF to chaos-gcc@4.7.1-reldebug.sh.
I also replaced calls to shroud_c_loc with c_loc.  Now users of 4.7.1 will
get a compile error instead of bad code.

    Error: Assumed-shape array 'value' at (1) cannot be an argument to the
    procedure 'c_loc' because it is not C interoperable

gcc 4.9.3, intel 15 and intel 16 all pass.
ATK-804