Force Fortran example to load with Fortran as linker:   set_target_properties(F_sidre_shocktube PROPERTIES LINKER_LANGUAGE Fortran) An alternative is to set CMAKE_Fortran_LINKER_PREFERENCE to a higher priority than CMAKE_CXX_LINKER_PREFERENCE.
This is required for intel otherwise:
/usr/lib/../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'

because it defines MAIN__ instead:
% nm F_sidre_shocktube.f.o | grep -i main
0000000000000000 T MAIN__